### ISSUE TITLE
TypeError - BYOWS_RPi

### ISSUE THREAD

**Issue by MartinSwanepoel** [jardiamj/BYOWS_RPi#7]
Keep getting this error. Can you maybe have a look why ?

pi@Weather:~/weather $ sudo PYTHONPATH=/usr/share/weewx python ./byows_rpi.py
Traceback (most recent call last):
  File "./byows_rpi.py", line 335, in <module>
    station = ByowsRpiStation()
  File "./byows_rpi.py", line 113, in __init__
    self.bme280_sensor.load_calibration_params(self.bme280_bus, self.bme280_address)
  File "/usr/local/lib/python2.7/dist-packages/bme280/__init__.py", line 153, in load_calibration_params
    compensation_params.dig_T1 = read.unsigned_short(0x88)
  File "/usr/local/lib/python2.7/dist-packages/bme280/reader.py", line 40, in unsigned_short
    return self._bus.read_word_data(self._address, register) & 0xffff
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 470, in read_word_data
    self._set_address(i2c_addr, force=force)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 354, in _set_address
    ioctl(self.fd, I2C_SLAVE, address)
TypeError: argument must be an int, or have a fileno() method

**Comment by randallgray** [comment]
Hi Martin,
Please post your code and I'll see what I can do...

--Randall

**Comment by jardiamj** [comment]
I am closing this issue because it is already 2 years old.
